version: '3.8'

services:
  # Note: Using MongoDB Atlas for testing as well with separate test database

  # Redis for testing
  redis-test:
    image: redis:7-alpine
    container_name: clipture-redis-test
    ports:
      - '6380:6379'
    networks:
      - clipture-test-network

  # Backend Tests
  backend-test:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: clipture-backend-test
    environment:
      - PORT=8080
      - ENV=test
      - LOG_LEVEL=warn
      - LOG_PRETTY=false
      - DB_NAME=${DB_NAME_TEST:-ytclipper_test}
      - MONGO_URI=${MONGO_URI_TEST}
    volumes:
      - ../backend:/app
    # No dependencies needed - using external MongoDB Atlas
    networks:
      - clipture-test-network
    command: ['go', 'test', './...']

  # Frontend Tests
  app-test:
    build:
      context: ../apps/app
      dockerfile: Dockerfile
      target: test
    container_name: clipture-app-test
    volumes:
      - ../apps/app:/app
    networks:
      - clipture-test-network
    command: ['npm', 'run', 'test']

  # Landing Page Tests
  landing-test:
    build:
      context: ../apps/landing
      dockerfile: Dockerfile
      target: test
    container_name: clipture-landing-test
    volumes:
      - ../apps/landing:/app
    networks:
      - clipture-test-network
    command: ['npm', 'run', 'test']

networks:
  clipture-test-network:
    driver: bridge
